// <auto-generated />
using System;
using Linksy.Infrastructure.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Linksy.Infrastructure.DAL.Migrations
{
    [DbContext(typeof(LinksyDbContext))]
    [Migration("20260107173811_RenameUrlIdColumn")]
    partial class RenameUrlIdColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("EngagementSequence");

            modelBuilder.HasSequence("ScanCodeSequence");

            modelBuilder.Entity("Linksy.Domain.Entities.LandingPage.LandingPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("DescriptionFontColor")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("EngagementCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TitleFontColor")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LaningPages", null, t =>
                        {
                            t.HasCheckConstraint("CK_LandingPage_EngagementCount", "\"EngagementCount\" >= 0");

                            t.HasCheckConstraint("CK_LandingPage_ViewCount", "\"ViewCount\" >= 0");
                        });
                });

            modelBuilder.Entity("Linksy.Domain.Entities.LandingPage.LandingPageItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClickCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LandingPageId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LandingPageId");

                    b.ToTable("LandingPageItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_LandingPageItem_ClickCount", "\"ClickCount\" >= 0");

                            t.HasCheckConstraint("CK_LandingPageItem_Order", "\"Order\" >= 0");
                        });

                    b.HasDiscriminator<string>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Linksy.Domain.Entities.ScanCode.ScanCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"ScanCodeSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ScanCount")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Linksy.Domain.Entities.Tracking.Engagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"EngagementSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<DateTime>("EngagedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Linksy.Domain.Entities.Tracking.LandingPageView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("LandingPageId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LandingPageId");

                    b.ToTable("LandingPageViews", (string)null);
                });

            modelBuilder.Entity("Linksy.Domain.Entities.Url.UmtParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UmtCampaign")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UmtMedium")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UmtSource")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UrlId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("VisitCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UrlId");

                    b.ToTable("UmtParameters", null, t =>
                        {
                            t.HasCheckConstraint("CK_UmtParameter_VisitCount", "\"VisitCount\" >= 0");
                        });
                });

            modelBuilder.Entity("Linksy.Domain.Entities.Url.Url", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("VisitCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Urls", null, t =>
                        {
                            t.HasCheckConstraint("CK_Url_VisitCount", "\"VisitCount\" >= 0");
                        });
                });

            modelBuilder.Entity("Linksy.Domain.Entities.User.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Linksy.Domain.Entities.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Linksy.Domain.Entities.LandingPage.ImageLandingPageItem", b =>
                {
                    b.HasBaseType("Linksy.Domain.Entities.LandingPage.LandingPageItem");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ImageLandingPageItem_AltText");

                    b.Property<int?>("UrlId")
                        .HasColumnType("integer")
                        .HasColumnName("ImageLandingPageItem_UrlId");

                    b.HasIndex("UrlId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_LandingPageItem_ClickCount", "\"ClickCount\" >= 0");

                            t.HasCheckConstraint("CK_LandingPageItem_Order", "\"Order\" >= 0");
                        });

                    b.HasDiscriminator().HasValue("Image");
                });

            modelBuilder.Entity("Linksy.Domain.Entities.LandingPage.TextLandingPageItem", b =>
                {
                    b.HasBaseType("Linksy.Domain.Entities.LandingPage.LandingPageItem");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("TextLandingPageItem_BackgroundColor");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("TextLandingPageItem_Content");

                    b.Property<string>("FontColor")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("TextLandingPageItem_FontColor");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_LandingPageItem_ClickCount", "\"ClickCount\" >= 0");

                            t.HasCheckConstraint("CK_LandingPageItem_Order", "\"Order\" >= 0");
                        });

                    b.HasDiscriminator().HasValue("Text");
                });

            modelBuilder.Entity("Linksy.Domain.Entities.LandingPage.UrlLandingPageItem", b =>
                {
                    b.HasBaseType("Linksy.Domain.Entities.LandingPage.LandingPageItem");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("UrlLandingPageItem_BackgroundColor");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("UrlLandingPageItem_Content");

                    b.Property<string>("FontColor")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("UrlLandingPageItem_FontColor");

                    b.Property<int>("UrlId")
                        .HasColumnType("integer")
                        .HasColumnName("UrlLandingPageItem_UrlId");

                    b.HasIndex("UrlId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_LandingPageItem_ClickCount", "\"ClickCount\" >= 0");

                            t.HasCheckConstraint("CK_LandingPageItem_Order", "\"Order\" >= 0");
                        });

                    b.HasDiscriminator().HasValue("Url");
                });

            modelBuilder.Entity("Linksy.Domain.Entities.LandingPage.YouTubeLandingPageItem", b =>
                {
                    b.HasBaseType("Linksy.Domain.Entities.LandingPage.LandingPageItem");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("YoutubeLandingPageItem_VideoUrl");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_LandingPageItem_ClickCount", "\"ClickCount\" >= 0");

                            t.HasCheckConstraint("CK_LandingPageItem_Order", "\"Order\" >= 0");
                        });

                    b.HasDiscriminator().HasValue("YouTube");
                });

            modelBuilder.Entity("Linksy.Domain.Entities.ScanCode.Barcode", b =>
                {
                    b.HasBaseType("Linksy.Domain.Entities.ScanCode.ScanCode");

                    b.Property<int>("UrlId")
                        .HasColumnType("integer");

                    b.HasIndex("UrlId")
                        .IsUnique();

                    b.ToTable("Barcodes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Barcode_ScanCount", "\"ScanCount\" >= 0");
                        });
                });

            modelBuilder.Entity("Linksy.Domain.Entities.ScanCode.QrCode", b =>
                {
                    b.HasBaseType("Linksy.Domain.Entities.ScanCode.ScanCode");

                    b.Property<int?>("UmtParameterId")
                        .HasColumnType("integer");

                    b.Property<int?>("UrlId")
                        .HasColumnType("integer");

                    b.HasIndex("UmtParameterId")
                        .IsUnique();

                    b.HasIndex("UrlId")
                        .IsUnique();

                    b.ToTable("QrCodes", null, t =>
                        {
                            t.HasCheckConstraint("CK_QrCode_ScanCount", "\"ScanCount\" >= 0");
                        });
                });

            modelBuilder.Entity("Linksy.Domain.Entities.Tracking.BarcodeEngagement", b =>
                {
                    b.HasBaseType("Linksy.Domain.Entities.Tracking.Engagement");

                    b.Property<int>("BarcodeId")
                        .HasColumnType("integer");

                    b.HasIndex("BarcodeId");

                    b.ToTable("BarcodeEngagements", (string)null);
                });

            modelBuilder.Entity("Linksy.Domain.Entities.Tracking.LandingPageEngagement", b =>
                {
                    b.HasBaseType("Linksy.Domain.Entities.Tracking.Engagement");

                    b.Property<int>("LandingPageId")
                        .HasColumnType("integer");

                    b.HasIndex("LandingPageId");

                    b.ToTable("LadingPageEngagements", (string)null);
                });

            modelBuilder.Entity("Linksy.Domain.Entities.Tracking.QrCodeEngagement", b =>
                {
                    b.HasBaseType("Linksy.Domain.Entities.Tracking.Engagement");

                    b.Property<int>("QrCodeId")
                        .HasColumnType("integer");

                    b.HasIndex("QrCodeId");

                    b.ToTable("QrCodeEngagements", (string)null);
                });

            modelBuilder.Entity("Linksy.Domain.Entities.Tracking.UmtParameterEngagement", b =>
                {
                    b.HasBaseType("Linksy.Domain.Entities.Tracking.Engagement");

                    b.Property<int>("UmtParameterId")
                        .HasColumnType("integer");

                    b.HasIndex("UmtParameterId");

                    b.ToTable("UmtParameterEngagements", (string)null);
                });

            modelBuilder.Entity("Linksy.Domain.Entities.Tracking.UrlEngagement", b =>
                {
                    b.HasBaseType("Linksy.Domain.Entities.Tracking.Engagement");

                    b.Property<int>("UrlId")
                        .HasColumnType("integer");

                    b.HasIndex("UrlId");

                    b.ToTable("UrlEngagements", (string)null);
                });

            modelBuilder.Entity("Linksy.Domain.Entities.LandingPage.LandingPage", b =>
                {
                    b.OwnsOne("Linksy.Domain.ValueObjects.Image", "BackgroundImage", b1 =>
                        {
                            b1.Property<int>("LandingPageId")
                                .HasColumnType("integer");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("UrlPath")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.HasKey("LandingPageId");

                            b1.ToTable("LaningPages");

                            b1.WithOwner()
                                .HasForeignKey("LandingPageId");
                        });

                    b.OwnsOne("Linksy.Domain.ValueObjects.Image", "LogoImage", b1 =>
                        {
                            b1.Property<int>("LandingPageId")
                                .HasColumnType("integer");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("UrlPath")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.HasKey("LandingPageId");

                            b1.ToTable("LaningPages");

                            b1.WithOwner()
                                .HasForeignKey("LandingPageId");
                        });

                    b.Navigation("BackgroundImage");

                    b.Navigation("LogoImage");
                });

            modelBuilder.Entity("Linksy.Domain.Entities.LandingPage.LandingPageItem", b =>
                {
                    b.HasOne("Linksy.Domain.Entities.LandingPage.LandingPage", "LandingPage")
                        .WithMany("LandingPageItems")
                        .HasForeignKey("LandingPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandingPage");
                });

            modelBuilder.Entity("Linksy.Domain.Entities.Tracking.LandingPageView", b =>
                {
                    b.HasOne("Linksy.Domain.Entities.LandingPage.LandingPage", "LandingPage")
                        .WithMany("Views")
                        .HasForeignKey("LandingPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandingPage");
                });

            modelBuilder.Entity("Linksy.Domain.Entities.Url.UmtParameter", b =>
                {
                    b.HasOne("Linksy.Domain.Entities.Url.Url", "Url")
                        .WithMany("UmtParameters")
                        .HasForeignKey("UrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Url");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Linksy.Domain.Entities.User.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Linksy.Domain.Entities.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Linksy.Domain.Entities.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Linksy.Domain.Entities.User.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Linksy.Domain.Entities.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Linksy.Domain.Entities.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Linksy.Domain.Entities.LandingPage.ImageLandingPageItem", b =>
                {
                    b.HasOne("Linksy.Domain.Entities.Url.Url", "Url")
                        .WithMany("ImageLandingPageItems")
                        .HasForeignKey("UrlId");

                    b.OwnsOne("Linksy.Domain.ValueObjects.Image", "Image", b1 =>
                        {
                            b1.Property<int>("ImageLandingPageItemId")
                                .HasColumnType("integer");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("ImageLandingPageItem_Image_FileName");

                            b1.Property<string>("UrlPath")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("ImageLandingPageItem_Image_UrlPath");

                            b1.HasKey("ImageLandingPageItemId");

                            b1.ToTable("LandingPageItems");

                            b1.WithOwner()
                                .HasForeignKey("ImageLandingPageItemId");
                        });

                    b.Navigation("Image")
                        .IsRequired();

                    b.Navigation("Url");
                });

            modelBuilder.Entity("Linksy.Domain.Entities.LandingPage.UrlLandingPageItem", b =>
                {
                    b.HasOne("Linksy.Domain.Entities.Url.Url", "Url")
                        .WithMany("UrlLandingPageItems")
                        .HasForeignKey("UrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Url");
                });

            modelBuilder.Entity("Linksy.Domain.Entities.ScanCode.Barcode", b =>
                {
                    b.HasOne("Linksy.Domain.Entities.Url.Url", "Url")
                        .WithOne("Barcode")
                        .HasForeignKey("Linksy.Domain.Entities.ScanCode.Barcode", "UrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Linksy.Domain.ValueObjects.Image", "ScanCodeImage", b1 =>
                        {
                            b1.Property<int>("BarcodeId")
                                .HasColumnType("integer");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("UrlPath")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.HasKey("BarcodeId");

                            b1.ToTable("Barcodes");

                            b1.WithOwner()
                                .HasForeignKey("BarcodeId");
                        });

                    b.Navigation("ScanCodeImage")
                        .IsRequired();

                    b.Navigation("Url");
                });

            modelBuilder.Entity("Linksy.Domain.Entities.ScanCode.QrCode", b =>
                {
                    b.HasOne("Linksy.Domain.Entities.Url.UmtParameter", "UmtParameter")
                        .WithOne("QrCode")
                        .HasForeignKey("Linksy.Domain.Entities.ScanCode.QrCode", "UmtParameterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Linksy.Domain.Entities.Url.Url", "Url")
                        .WithOne("QrCode")
                        .HasForeignKey("Linksy.Domain.Entities.ScanCode.QrCode", "UrlId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Linksy.Domain.ValueObjects.Image", "ScanCodeImage", b1 =>
                        {
                            b1.Property<int>("QrCodeId")
                                .HasColumnType("integer");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("UrlPath")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.HasKey("QrCodeId");

                            b1.ToTable("QrCodes");

                            b1.WithOwner()
                                .HasForeignKey("QrCodeId");
                        });

                    b.Navigation("ScanCodeImage")
                        .IsRequired();

                    b.Navigation("UmtParameter");

                    b.Navigation("Url");
                });

            modelBuilder.Entity("Linksy.Domain.Entities.Tracking.BarcodeEngagement", b =>
                {
                    b.HasOne("Linksy.Domain.Entities.ScanCode.Barcode", "Barcode")
                        .WithMany("Engagements")
                        .HasForeignKey("BarcodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barcode");
                });

            modelBuilder.Entity("Linksy.Domain.Entities.Tracking.LandingPageEngagement", b =>
                {
                    b.HasOne("Linksy.Domain.Entities.LandingPage.LandingPage", "LandingPage")
                        .WithMany("Engagements")
                        .HasForeignKey("LandingPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandingPage");
                });

            modelBuilder.Entity("Linksy.Domain.Entities.Tracking.QrCodeEngagement", b =>
                {
                    b.HasOne("Linksy.Domain.Entities.ScanCode.QrCode", "QrCode")
                        .WithMany("Engagements")
                        .HasForeignKey("QrCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QrCode");
                });

            modelBuilder.Entity("Linksy.Domain.Entities.Tracking.UmtParameterEngagement", b =>
                {
                    b.HasOne("Linksy.Domain.Entities.Url.UmtParameter", "UmtParameter")
                        .WithMany("Engagements")
                        .HasForeignKey("UmtParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UmtParameter");
                });

            modelBuilder.Entity("Linksy.Domain.Entities.Tracking.UrlEngagement", b =>
                {
                    b.HasOne("Linksy.Domain.Entities.Url.Url", "Url")
                        .WithMany("Engagements")
                        .HasForeignKey("UrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Url");
                });

            modelBuilder.Entity("Linksy.Domain.Entities.LandingPage.LandingPage", b =>
                {
                    b.Navigation("Engagements");

                    b.Navigation("LandingPageItems");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("Linksy.Domain.Entities.Url.UmtParameter", b =>
                {
                    b.Navigation("Engagements");

                    b.Navigation("QrCode");
                });

            modelBuilder.Entity("Linksy.Domain.Entities.Url.Url", b =>
                {
                    b.Navigation("Barcode");

                    b.Navigation("Engagements");

                    b.Navigation("ImageLandingPageItems");

                    b.Navigation("QrCode");

                    b.Navigation("UmtParameters");

                    b.Navigation("UrlLandingPageItems");
                });

            modelBuilder.Entity("Linksy.Domain.Entities.ScanCode.Barcode", b =>
                {
                    b.Navigation("Engagements");
                });

            modelBuilder.Entity("Linksy.Domain.Entities.ScanCode.QrCode", b =>
                {
                    b.Navigation("Engagements");
                });
#pragma warning restore 612, 618
        }
    }
}
